/** @type {import('tailwindcss').Config} */
// Design tokens sourced from the Claude Project doc `precision_retail_core.md`
// (the "Precision Retail Core" design system spec) — colors, typography,
// spacing and radius are taken verbatim from its YAML frontmatter, per
// claude/README.md Section 10 ("build tailwind.config.js from
// precision_retail_core.md, not from a screen's embedded config").
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#434655',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#747686',
        'outline-variant': '#c4c5d7',
        'surface-tint': '#2151da',
        primary: '#0037b0',
        'on-primary': '#ffffff',
        'primary-container': '#1d4ed8',
        'on-primary-container': '#cad3ff',
        'inverse-primary': '#b7c4ff',
        secondary: '#565e74',
        'on-secondary': '#ffffff',
        'secondary-container': '#dae2fd',
        'on-secondary-container': '#5c647a',
        tertiary: '#004870',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006194',
        'on-tertiary-container': '#b2d9ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001551',
        'on-primary-fixed-variant': '#0039b5',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'tertiary-fixed': '#cce5ff',
        'tertiary-fixed-dim': '#93ccff',
        'on-tertiary-fixed': '#001d31',
        'on-tertiary-fixed-variant': '#004b73',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      fontFamily: {
        'display-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'label-numeric-lg': ['"JetBrains Mono"', 'monospace'],
        'label-numeric-md': ['"JetBrains Mono"', 'monospace'],
        'label-numeric-sm': ['"JetBrains Mono"', 'monospace'],
        'label-code': ['"JetBrains Mono"', 'monospace'],
        'label-badge': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-numeric-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-numeric-md': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-numeric-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-code': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'touch-target-min': '2.75rem',
        'pos-sidebar-width': '16rem',
        'pos-cart-width': '24rem',
        'gutter-default': '1rem',
      },
    },
  },
  plugins: [],
}
